/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as UserSettingsSubscriptionsRouteImport } from './routes/user-settings/subscriptions'
import { Route as UserSettingsGeneralRouteImport } from './routes/user-settings/general'
import { Route as UserSettingsDeleteAccountRouteImport } from './routes/user-settings/delete-account'
import { Route as ProjectsProjectSlugSchemasRouteImport } from './routes/projects/$projectSlug/schemas'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsSubscriptionsRoute =
  UserSettingsSubscriptionsRouteImport.update({
    id: '/user-settings/subscriptions',
    path: '/user-settings/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserSettingsGeneralRoute = UserSettingsGeneralRouteImport.update({
  id: '/user-settings/general',
  path: '/user-settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsDeleteAccountRoute =
  UserSettingsDeleteAccountRouteImport.update({
    id: '/user-settings/delete-account',
    path: '/user-settings/delete-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectSlugSchemasRoute =
  ProjectsProjectSlugSchemasRouteImport.update({
    id: '/projects/$projectSlug/schemas',
    path: '/projects/$projectSlug/schemas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user-settings/delete-account': typeof UserSettingsDeleteAccountRoute
  '/user-settings/general': typeof UserSettingsGeneralRoute
  '/user-settings/subscriptions': typeof UserSettingsSubscriptionsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectSlug/schemas': typeof ProjectsProjectSlugSchemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user-settings/delete-account': typeof UserSettingsDeleteAccountRoute
  '/user-settings/general': typeof UserSettingsGeneralRoute
  '/user-settings/subscriptions': typeof UserSettingsSubscriptionsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectSlug/schemas': typeof ProjectsProjectSlugSchemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user-settings/delete-account': typeof UserSettingsDeleteAccountRoute
  '/user-settings/general': typeof UserSettingsGeneralRoute
  '/user-settings/subscriptions': typeof UserSettingsSubscriptionsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectSlug/schemas': typeof ProjectsProjectSlugSchemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/user-settings/delete-account'
    | '/user-settings/general'
    | '/user-settings/subscriptions'
    | '/projects'
    | '/projects/$projectSlug/schemas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/user-settings/delete-account'
    | '/user-settings/general'
    | '/user-settings/subscriptions'
    | '/projects'
    | '/projects/$projectSlug/schemas'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/user-settings/delete-account'
    | '/user-settings/general'
    | '/user-settings/subscriptions'
    | '/projects/'
    | '/projects/$projectSlug/schemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UserSettingsDeleteAccountRoute: typeof UserSettingsDeleteAccountRoute
  UserSettingsGeneralRoute: typeof UserSettingsGeneralRoute
  UserSettingsSubscriptionsRoute: typeof UserSettingsSubscriptionsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectSlugSchemasRoute: typeof ProjectsProjectSlugSchemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings/subscriptions': {
      id: '/user-settings/subscriptions'
      path: '/user-settings/subscriptions'
      fullPath: '/user-settings/subscriptions'
      preLoaderRoute: typeof UserSettingsSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings/general': {
      id: '/user-settings/general'
      path: '/user-settings/general'
      fullPath: '/user-settings/general'
      preLoaderRoute: typeof UserSettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings/delete-account': {
      id: '/user-settings/delete-account'
      path: '/user-settings/delete-account'
      fullPath: '/user-settings/delete-account'
      preLoaderRoute: typeof UserSettingsDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/schemas': {
      id: '/projects/$projectSlug/schemas'
      path: '/projects/$projectSlug/schemas'
      fullPath: '/projects/$projectSlug/schemas'
      preLoaderRoute: typeof ProjectsProjectSlugSchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UserSettingsDeleteAccountRoute: UserSettingsDeleteAccountRoute,
  UserSettingsGeneralRoute: UserSettingsGeneralRoute,
  UserSettingsSubscriptionsRoute: UserSettingsSubscriptionsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectSlugSchemasRoute: ProjectsProjectSlugSchemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
