/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSettingsRouteImport } from './routes/user-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdSchemasRouteImport } from './routes/projects/$projectId/schemas'

const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSchemasRoute =
  ProjectsProjectIdSchemasRouteImport.update({
    id: '/projects/$projectId/schemas',
    path: '/projects/$projectId/schemas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-settings': typeof UserSettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/schemas': typeof ProjectsProjectIdSchemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-settings': typeof UserSettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/schemas': typeof ProjectsProjectIdSchemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user-settings': typeof UserSettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/schemas': typeof ProjectsProjectIdSchemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user-settings'
    | '/projects'
    | '/projects/$projectId/schemas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user-settings' | '/projects' | '/projects/$projectId/schemas'
  id:
    | '__root__'
    | '/'
    | '/user-settings'
    | '/projects/'
    | '/projects/$projectId/schemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserSettingsRoute: typeof UserSettingsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdSchemasRoute: typeof ProjectsProjectIdSchemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/schemas': {
      id: '/projects/$projectId/schemas'
      path: '/projects/$projectId/schemas'
      fullPath: '/projects/$projectId/schemas'
      preLoaderRoute: typeof ProjectsProjectIdSchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserSettingsRoute: UserSettingsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdSchemasRoute: ProjectsProjectIdSchemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
